game_name: "CartPole-v1"
render: true
episodes: 250
policy_name: "alphazero"

policies:
  alphazero:
    n_explore: 200
    c: 1.0
    buffer_size: 1000
    batch_size: 128
    update_every: 1
    max_reward: 500